

export default function(){
  return {
    order: [
      "activeCards",
      "card_name",
      "typePromo",
      "description",
      "binding",
      "ownBreed",
      "ownBreedMother",
      "ownBreedFather",
      "date_berth",
      "gender",
      "bearTest",
      "hd",
      "pl",
      "privit",
      "photo_parents",
      "pomet",
      "cleymenie",
      "chipirovanie",
      "promo_photos",
      "price_group",
      "price_single",
      "price_knit",
      "date_berth_month",
      "pomet_price",
      "serf_porodi_vazka",
    ],
    activeCards: {
      type:"switch",
      name: "activeCards", 
      label: "Статус", 
      options: [
        {name:"Активно",value:"on"},
        {name:"Не активно", value:"off"},
      ],
      wrapClass: "col-12 account-item num-offset-top"
    },
    card_name:{
      type:"text", 
      name: "card_name",  
      label:"Наименование объявления*", 
      wrapClass: "col-12 account-item input-animate-label",
      validate: ['required', 'minLength'],
      num:"01"
    },
    typePromo: {
      type:"showByClick",
      name: "typePromo", 
      label:"Тип объявления", 
      wrapClass: "col-12 account-item account-item-checkbox",
      num: "02",
      options:[
        {label: "Продажа", value:"sale"},
        {label: "Анонс помета", value:"anons"},
        {label: "Вязка", value:"knit"},
        {label: "В дар", value:"gift"},
      ]
    },
    binding:{
      type:"binding", 
      name: "binding",  
      label:"Выбрать компанию*", 
      wrapClass: "col-12 account-item account-item-checkbox",
      options: [
      ],
      num:"03"
    },
    ownBreed:{
      type:"ownBreeds", 
      name: "knitBreed",  
      label:"Выбрать животное", 
      // filter: 'Мама',
      wrapClass: "col-12 account-item account-item-checkbox",
      options: [
      ],
      num:"01",
      hideByClickId: 'knit',
    },
    ownBreedMother:{
      type:"ownBreeds", 
      name: "ownBreedMother",  
      label:"Выбрать маму", 
      filter: 'Мама',
      wrapClass: "col-12 account-item account-item-checkbox",
      options: [
      ],
      num:"01",
      hideByClickId: 'sale anons gift',
    },
    ownBreedFather:{
      type:"ownBreeds", 
      name: "ownBreedFather",  
      label:"Выбрать папу", 
      filter: 'Папа',
      wrapClass: "col-12 account-item account-item-checkbox",
      options: [
      ],
      num:"01",
      hideByClickId: 'sale anons gift',
    },
    gender: {
      type: "radio", 
      label:"Пол", 
      name: "gender", 
      wrapClass: "col-12 account-item account-item-checkbox",
      num: "02",
      hideByClickId: 'sale',
      options:[
        {label: "Девочка", value:"women"},
        {label: "Мальчик", value:"men"},
      ]
    },
    bearTest: {
      type: "radio", 
      label:"BAER-test", 
      name: "bearTest", 
      wrapClass: "col-12 account-item account-item-checkbox",
      num: "04",
      options:[
        {label: "+/+", value:"+/+"},
        {label: "-/+", value:"-/+"},
        {label: "+/-", value:"+/-"},
        {label: "-/-", value:"-/-"},
      ],
      hideByClickId: 'sale gift',
    },
    hd: {
      type:"switch",
      name: "hd", 
      label: "Сертификат на отсутствие дисплазии (HD)", 
      num: "05",
      options: [
        {name:"Нет", value:"off"},
        {name:"Есть",value:"on"},
        
      ],
      wrapClass: "col-12 account-item num-offset-top",
      hideByClickId: 'sale gift',
    },
    pl: {
      type:"switch",
      name: "pl", 
      label: "Сертификат на отсутствие пателлы (PL)", 
      num: "06",
      options: [
        {name:"Нет", value:"off"},
        {name:"Есть",value:"on"},
      ],
      wrapClass: "col-12 account-item num-offset-top",
      hideByClickId: 'sale gift',
    },
    privit: {
      type:"switch",
      name: "privit", 
      label: "Привит", 
      num: "07",
      options: [
        {name:"Нет", value:"off"},
        {name:"Да",value:"on"},
        
      ],
      wrapClass: "col-12 account-item num-offset-top",
      hideByClickId: 'sale gift',
    },
    pomet: {
      type:"radio",
      name: "pomet", 
      label: "Помет", 
      placeholder: "Выбрать помет",
      num: "08",
      options: [
        {label: "A", value:"type_1"},
        {label: "B", value:"type_2"},
        {label: "C", value:"type_3"},
        {label: "D", value:"type_4"},
        {label: "E", value:"type_5"},
        {label: "F", value:"type_6"},
        {label: "G", value:"type_7"},
        {label: "H", value:"type_8"},
        {label: "I", value:"type_9"},
        {label: "J", value:"type_10"},
        {label: "K", value:"type_11"},
        {label: "L", value:"type_12"},
        {label: "M", value:"type_13"},
        {label: "N", value:"type_14"},
        {label: "O", value:"type_15"},
      ],
      wrapClass: "col-12 account-item num-offset-top",
      hideByClickId: 'sale gift',
    },
    date_berth:{
      type:"date", 
      name: "date_berth",  
      label:"Дата рождения", 
      wrapClass: "col-12 account-item input-animate-label",
      num:"12",
      hideByClickId: 'sale',
    },
    cleymenie: {
      type:"switch",
      name: "cleymenie", 
      label: "Клеймение", 
      num: "09",
      options: [
        {name:"Нет", value:"off"},
        {name:"Да",value:"on"},
       
      ],
      wrapClass: "col-12 account-item num-offset-top",
      hideByClickId: 'sale gift',
    },
    chipirovanie: {
      type:"switch",
      name: "chipirovanie", 
      label: "Чипирование", 
      num: "10",
      options: [
        {name:"Нет", value:"off"},
        {name:"Да",value:"on"},
      ],
      wrapClass: "col-12 account-item num-offset-top",
      hideByClickId: 'sale gift',
    },
    promo_photos: {
      type: "dropzone", 
      name: "promo_photos", 
      label:"Загрузите фото объявления", 
      labelSecond:"Вы можете загрузить до 10 файлов. Вес каждого файла не должен превышать 500 Кб. Допустимый формат файлов: *.jpg, *.png. Рекомендуемый формат вертикальный - 2:1 (Ширина 1920px, Высота 960px).", 
      typeFile: "img", 
      typeUpload:".png, .jpg, .jpeg", 
      maxSize: 5242880, 
      num: "06",
      wrapClass: "col-12 col-lg-3 col-sm-5 account-item  img-item-input",
      hideByClickId: 'sale gift',
    },
    photo_parents: {
      type: "file", 
      name: "photo_parents", 
      label:"Загрузите фото родитлей", 
      labelSecond:"Вы можете загрузить до 10 файлов. Вес каждого файла не должен превышать 500 Кб. Допустимый формат файлов: *.jpg, *.png. Рекомендуемый формат вертикальный - 2:1 (Ширина 1920px, Высота 960px).", 
      typeFile: "img", 
      typeUpload:".png, .jpg, .jpeg", 
      maxSize: 5242880, 
      wrapClass: "col-12 col-lg-3 col-sm-5 account-item  img-item-input",
      hideByClickId: 'anons',
    },
    price_group:{
      type: "multy", 
      mainname: "price_group", 
      label:"Стоимость за щенка/котенка", 
      labelSecond:"Заполните какое-то одно поле. От/до или фиксируемую стоимость", 
      wrapClass: "col-12 account-item",
      validate: ['required', 'minLength'],
      hideByClickId: "sale",
      allFields: [
        { 
          type:"text", 
          name: "from", 
          label: "от", 
          wrapClass: "col-6 account-item input-animate-label",
        },
        { 
          type:"text", 
          name: "to", 
          label: "до", 
          wrapClass: "col-6 account-item input-animate-label",
        },
      ],
    },
    price_single:{
      type:"text", 
      name: "price_single",  
      label:"Стоимость за щенка/котенка", 
      labelSecond:"Заполните какое-то одно поле. От/до или фиксируемую стоимость", 
      wrapClass: "col-12 account-item input-animate-label",
      validate: ['required', 'minLength'],
      hideByClickId: 'sale',
    },
    price_knit:{
      type:"text", 
      name: "price_knit",  
      label:"Стоимость ", 
      wrapClass: "col-12 account-item input-animate-label",
      validate: ['required', 'minLength'],
      hideByClickId: 'knit',
    },
    description:{
      type:"textarea", 
      name: "description",  
      label:"Описание", 
      wrapClass: "col-12 account-item input-animate-label",
      validate: ['required', 'minLength'],
      
      hideByClickId: 'knit',
    },
    date_berth_month:{
      type:"checkbox", 
      name: "date_berth_month",  
      label:"Выберите месяц ожидаемого помета", 
      wrapClass: "col-12 account-item num-offset-top",
      view: "months",
      options: [
        {label: "Январь", value:"type_1"},
        {label: "Февраль", value:"type_2"},
        {label: "Март", value:"type_3"},
        {label: "Апрель", value:"type_4"},
        {label: "Май", value:"type_5"},
        {label: "Июнь", value:"type_6"},
        {label: "Июль", value:"type_7"},
        {label: "Август", value:"type_8"},
        {label: "Сентябрь", value:"type_9"},
        {label: "Октябрь", value:"type_10"},
        {label: "Ноябрь", value:"type_11"},
        {label: "Декабрь", value:"type_12"},
      ],
      hideByClickId: "anons",
    },
    pomet_price: {
      type: "multy", 
      mainname: "pomet_price", 
      label:"Стоимость",  
      wrapClass: "col-12 account-item",
      hideByClickId: "anons",
      allFields: [
        { 
          type:"text", 
          name: "from", 
          label: "от", 
          wrapClass: "col-6 account-item input-animate-label",
        },
        { 
          type:"text", 
          name: "to", 
          label: "до", 
          wrapClass: "col-6 account-item input-animate-label",
        },
      ],
    },
    serf_porodi_vazka: {
      type:"switch",
      name: "serf_porodi_vazka", 
      label: "Сертификат породы", 
      options: [
        {name:"Нет", value:"off"},
        {name:"Есть",value:"on"},
        
      ],
      wrapClass: "col-12 account-item num-offset-top",
      hideByClickId: 'pomet',
    },
    // gender_vazka: {
    //   type: "radio", 
    //   label:"Пол", 
    //   name: "gender_vazka", 
    //   wrapClass: "col-12 account-item account-item-checkbox",
    //   num: "02",
    //   hideByClickId: 'knit',
    //   options:[
    //     {label: "Девочка", value:"women"},
    //     {label: "Мальчик", value:"men"},
    //   ]
    // },
    // work_dog_serf_vazka: {
    //   type:"switch",
    //   name: "work_dog_serf_vazka", 
    //   label: "Сертификат по рабочим качествам собаки", 
    //   num: "05",
    //   options: [
    //     {name:"Нет", value:"off"},
    //     {name:"Есть",value:"on"},
        
    //   ],
    //   wrapClass: "col-12 account-item num-offset-top",
    //   hideByClickId: 'knit',
    // },
    // kerenga_vazka: {
    //   type:"switch",
    //   name: "kerenga_vazka", 
    //   label: "Свидетельство о прохождении племенного отбора (Керунга)", 
    //   num: "05",
    //   options: [
    //     {name:"Нет", value:"off"},
    //     {name:"Есть",value:"on"},
        
    //   ],
    //   wrapClass: "col-12 account-item num-offset-top",
    //   hideByClickId: 'knit',
    // },
    // titul_chempiona_vazka: {
    //   type:"switch",
    //   name: "titul_chempiona_vazka", 
    //   label: "Титул интерчемпиона", 
    //   num: "05",
    //   options: [
    //     {name:"Нет", value:"off"},
    //     {name:"Есть",value:"on"},
        
    //   ],
    //   wrapClass: "col-12 account-item num-offset-top",
    //   hideByClickId: 'knit',
    // },

    // diplomi_vazka:{
    //   type:"textarea", 
    //   name: "diplomi_vazka",  
    //   label:"Дипломы", 
    //   labelSecond:"Длина текста не должна превышать 300 символов, включая пробелы.", 
    //   wrapClass: "col-12 account-item input-animate-label",
    //   num: "04",
    //   maxLength: 110,
    //   hideByClickId: 'knit',
    // },
    // vistovki_vazka:{
    //   type:"textarea", 
    //   name: "vistovki_vazka",  
    //   label:"Участие в выставках", 
    //   labelSecond:"Длина текста не должна превышать 300 символов, включая пробелы.", 
    //   wrapClass: "col-12 account-item input-animate-label",
    //   num: "04",
    //   maxLength: 110,
    //   hideByClickId: 'knit',
    // },
    // tituli_vazka:{
    //   type:"textarea", 
    //   name: "tituli_vazka",  
    //   label:"Перечислите титулы (через запятую)", 
    //   labelSecond:"Длина текста не должна превышать 300 символов, включая пробелы.", 
    //   wrapClass: "col-12 account-item input-animate-label",
    //   num: "04",
    //   maxLength: 110,
    //   hideByClickId: 'knit',
    // },
  }
}